# Generated by Django 6.0.6 on 2026-06-28 11:32

import django.core.validators
import users.validators
from django.db import migrations, models


def blank_url_avatars(apps, schema_editor):
    # Los avatares antiguos eran URLs (URLField). Como ahora es un ImageField
    # que espera una ruta dentro de MEDIA_ROOT, esos valores quedarían rotos
    # (<img src="/media/https://...">). Se vacían (no había datos reales).
    User = apps.get_model('users', 'User')
    User.objects.exclude(avatar='').update(avatar='')


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagen de perfil (PNG, JPG o WEBP, máx. 2 MB).', upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp']), users.validators.MaxFileSizeValidator(2097152)]),
        ),
        migrations.RunPython(blank_url_avatars, reverse_noop),
    ]
