# Generated by Django 6.0.6 on 2026-06-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_brand',
            field=models.CharField(blank=True, choices=[('flowly', 'Flowly'), ('nsw', 'NoSoloWebs')], default='', help_text='Tema visual preferido. Vacío = heredar de la organización.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_mode',
            field=models.CharField(blank=True, choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='', help_text='Claro u oscuro. Vacío = automático (según sistema/organización).', max_length=10),
        ),
    ]
