# Generated by Django 6.0.6 on 2026-06-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_theme_brand_user_theme_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status_message',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='status_state',
            field=models.CharField(choices=[('available', 'Disponible'), ('working', 'Concentrado'), ('busy', 'Ocupado'), ('away', 'Ausente')], default='available', max_length=10),
        ),
    ]
