# Generated by Django 6.0.6 on 2026-06-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_last_seen_user_status_message_user_status_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='char_hair',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='char_hair_style',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='char_shirt',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='char_skin',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
