# Generated by Django 6.0.6 on 2026-06-29 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_org_from_board(apps, schema_editor):
    """Asigna la organización de cada notificación a partir de su board (las
    notificaciones existentes se crearon desde tableros)."""
    Notification = apps.get_model('collab', 'Notification')
    for n in Notification.objects.filter(board__isnull=False, organization__isnull=True).select_related('board'):
        n.organization_id = n.board.organization_id
        n.save(update_fields=['organization'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_board_description_alter_board_name_and_more'),
        ('collab', '0002_alter_message_board_channel_message_channel_and_more'),
        ('organizations', '0003_organization_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='collab_noti_recipie_6ee1f5_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.RunPython(backfill_org_from_board, noop),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'organization', 'unread'], name='collab_noti_recipie_111e8d_idx'),
        ),
    ]
