# Generated by Django 6.0.6 on 2026-07-03 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_board_description_alter_board_name_and_more'),
        ('collab', '0003_remove_notification_collab_noti_recipie_6ee1f5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('board__isnull', False), ('channel__isnull', True)), models.Q(('board__isnull', True), ('channel__isnull', False)), _connector='OR'), name='message_board_xor_channel'),
        ),
    ]
