# Generated by Django 6.0.6 on 2026-06-25 19:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('is_personal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_accent', models.CharField(blank=True, help_text='Color de acento #RRGGBB. Vacío = indigo de Flowly.', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')])),
                ('brand_accent_hover', models.CharField(blank=True, help_text='Acento al pasar el ratón. Vacío = igual que el acento.', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')])),
                ('brand_bg_primary', models.CharField(blank=True, help_text='Fondo principal #RRGGBB. Vacío = el del modo activo.', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')])),
                ('on_accent_mode', models.CharField(choices=[('auto', 'Automático (contraste)'), ('light', 'Texto claro'), ('dark', 'Texto oscuro')], default='auto', help_text='Color del texto sobre el acento. Automático elige por contraste.', max_length=10)),
                ('font_display', models.CharField(blank=True, choices=[('', 'Flowly (Space Grotesk)'), ('ppgoshasans', 'PP Gosha Sans')], default='', max_length=20)),
                ('theme_mode', models.CharField(choices=[('dark', 'Oscuro'), ('light', 'Claro'), ('auto', 'Automático')], default='dark', help_text='Modo por defecto de la organización (el usuario puede cambiarlo).', max_length=10)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'organization theme',
                'verbose_name_plural': 'organization themes',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization membership',
                'verbose_name_plural': 'organization memberships',
                'ordering': ['organization', 'user'],
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
