# Generated by Django 6.0.6 on 2026-06-26 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtheme',
            name='brand_bg_active',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='organizationtheme',
            name='brand_bg_elevated',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='organizationtheme',
            name='brand_bg_hover',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='organizationtheme',
            name='brand_bg_secondary',
            field=models.CharField(blank=True, help_text='Fondo de superficies (columnas/tarjetas).', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='organizationtheme',
            name='brand_bg_tertiary',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='organizationtheme',
            name='brand_overlay',
            field=models.CharField(blank=True, help_text='Color base de bordes/scrollbar.', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='organizationtheme',
            name='brand_success',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='organizationtheme',
            name='brand_text_primary',
            field=models.CharField(blank=True, help_text='Texto principal.', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='organizationtheme',
            name='brand_text_secondary',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='organizationtheme',
            name='brand_text_tertiary',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='organizationtheme',
            name='brand_warning',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='organizationtheme',
            name='font_body',
            field=models.CharField(blank=True, choices=[('', 'Por defecto (Flowly)'), ('spacegrotesk', 'Space Grotesk'), ('mulish', 'Mulish'), ('inter', 'Inter'), ('ibmplexsans', 'IBM Plex Sans'), ('ppgoshasans', 'PP Gosha Sans')], default='', help_text='Fuente del cuerpo de texto.', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationtheme',
            name='brand_accent',
            field=models.CharField(blank=True, help_text='Acento #RRGGBB. Vacío = indigo de Flowly.', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AlterField(
            model_name='organizationtheme',
            name='brand_bg_primary',
            field=models.CharField(blank=True, help_text='Fondo principal (página).', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal con el formato #RRGGBB.', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AlterField(
            model_name='organizationtheme',
            name='font_display',
            field=models.CharField(blank=True, choices=[('', 'Por defecto (Flowly)'), ('spacegrotesk', 'Space Grotesk'), ('mulish', 'Mulish'), ('inter', 'Inter'), ('ibmplexsans', 'IBM Plex Sans'), ('ppgoshasans', 'PP Gosha Sans')], default='', help_text='Fuente de titulares/UI.', max_length=20),
        ),
    ]
