# Generated by Django 6.0.6 on 2026-06-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationtheme_brand_bg_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='brand',
            field=models.CharField(choices=[('flowly', 'Flowly'), ('nsw', 'NoSoloWebs')], default='flowly', help_text='Marca/tema visual (define data-brand en el front).', max_length=20),
        ),
    ]
