# Generated by Django 4.2.30 on 2026-05-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Card headline displayed on the board.', max_length=256)),
                ('description', models.TextField(blank=True, help_text='Detailed description shown when the card is opened.')),
                ('order', models.PositiveIntegerField(help_text='Zero-based vertical position within the column.')),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=0, help_text='Urgency level (0=none, 4=urgent).')),
                ('due_date', models.DateField(blank=True, help_text='Optional deadline. Displayed as a warning when overdue.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'card',
                'verbose_name_plural': 'cards',
                'ordering': ['order'],
            },
        ),
    ]
