# Generated by Django 4.2.30 on 2026-05-14 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0002_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='User responsible for completing this card.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='column',
            field=models.ForeignKey(help_text='The column this card belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.column'),
        ),
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Colored tags for categorization.', related_name='cards', to='boards.label'),
        ),
    ]
