# Tests de organizaciones: modelos, servicio, middleware, tema y scoping.

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import IntegrityError, transaction
from django.test import TestCase
from django.urls import reverse

from boards.models import Board
from organizations.models import (
    Organization,
    OrganizationMembership,
    OrganizationTheme,
)
from organizations.services import get_or_create_personal_organization

User = get_user_model()


class OrganizationModelTests(TestCase):
    def test_slug_autogenerated_and_deduped(self):
        a = Organization.objects.create(name='Acme Inc')
        b = Organization.objects.create(name='Acme Inc')
        self.assertEqual(a.slug, 'acme-inc')
        self.assertTrue(b.slug.startswith('acme-inc'))
        self.assertNotEqual(a.slug, b.slug)

    def test_membership_unique_per_user_and_org(self):
        org = Organization.objects.create(name='Acme')
        user = User.objects.create_user('u1', password='pass12345')
        OrganizationMembership.objects.create(organization=org, user=user, role='admin')
        with self.assertRaises(IntegrityError):
            with transaction.atomic():
                OrganizationMembership.objects.create(organization=org, user=user, role='member')

    def test_theme_rejects_invalid_hex(self):
        org = Organization.objects.create(name='Acme')
        theme = OrganizationTheme(organization=org, brand_accent='nothex')
        with self.assertRaises(ValidationError):
            theme.full_clean()

    def test_theme_accepts_valid_hex(self):
        org = Organization.objects.create(name='Acme')
        theme = OrganizationTheme(organization=org, brand_accent='#d6ff00')
        theme.full_clean()  # no debe lanzar


class PersonalOrgServiceTests(TestCase):
    def test_creates_personal_org_with_owner_membership(self):
        user = User.objects.create_user('u1', password='pass12345')
        org = get_or_create_personal_organization(user)
        self.assertTrue(org.is_personal)
        membership = OrganizationMembership.objects.get(user=user)
        self.assertEqual(membership.organization, org)
        self.assertEqual(membership.role, 'owner')

    def test_idempotent(self):
        user = User.objects.create_user('u1', password='pass12345')
        first = get_or_create_personal_organization(user)
        second = get_or_create_personal_organization(user)
        self.assertEqual(first.pk, second.pk)
        self.assertEqual(OrganizationMembership.objects.filter(user=user).count(), 1)


class OnAccentLuminanceTests(TestCase):
    def test_auto_chooses_dark_or_light_by_luminance(self):
        from flowly.context_processors import _hex_to_channels, _resolve_on_accent
        _, lime = _hex_to_channels('#d6ff00')
        _, indigo = _hex_to_channels('#6366F1')
        self.assertEqual(_resolve_on_accent('auto', lime), '17 24 39')      # lime -> texto oscuro
        self.assertEqual(_resolve_on_accent('auto', indigo), '255 255 255')  # indigo -> texto claro
        self.assertEqual(_resolve_on_accent('light', None), '255 255 255')
        self.assertEqual(_resolve_on_accent('dark', None), '17 24 39')


class OrgThemeInjectionTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.user = User.objects.create_user('lima', password='limapass1234')
        cls.org = Organization.objects.create(name='NoSoloWebs', slug='nosolowebs')
        OrganizationTheme.objects.create(
            organization=cls.org, brand_accent='#d6ff00',
            on_accent_mode='auto', font_display='ppgoshasans', theme_mode='dark',
        )
        OrganizationMembership.objects.create(organization=cls.org, user=cls.user, role='admin')

    def test_active_org_emits_brand_override(self):
        self.client.login(username='lima', password='limapass1234')
        html = self.client.get(reverse('home')).content.decode()
        self.assertIn('id="org-theme"', html)
        self.assertIn('--brand-accent:214 255 0;', html)
        self.assertIn('--brand-on-accent:17 24 39;', html)  # lime -> texto negro
        self.assertIn('PPGoshaSans', html)

    def test_user_without_theme_emits_no_override(self):
        plain = User.objects.create_user('plain', password='plainpass1234')
        org = Organization.objects.create(name='Plain Co')
        OrganizationMembership.objects.create(organization=org, user=plain, role='admin')
        self.client.login(username='plain', password='plainpass1234')
        html = self.client.get(reverse('home')).content.decode()
        self.assertNotIn('id="org-theme"', html)


class OrgSwitchTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.user = User.objects.create_user('sam', password='sampass1234')
        cls.org_a = Organization.objects.create(name='Org A')
        cls.org_b = Organization.objects.create(name='Org B')
        cls.foreign = Organization.objects.create(name='Foreign Co')
        OrganizationMembership.objects.create(organization=cls.org_a, user=cls.user, role='admin')
        OrganizationMembership.objects.create(organization=cls.org_b, user=cls.user, role='member')

    def test_switch_to_member_org(self):
        self.client.login(username='sam', password='sampass1234')
        self.client.post(reverse('org-switch'), {'organization': self.org_b.id})
        self.assertEqual(self.client.session['active_org_id'], self.org_b.id)

    def test_switch_to_non_member_is_rejected(self):
        self.client.login(username='sam', password='sampass1234')
        self.client.get(reverse('home'))  # fija la org activa por defecto
        before = self.client.session.get('active_org_id')
        self.client.post(reverse('org-switch'), {'organization': self.foreign.id})
        self.assertEqual(self.client.session.get('active_org_id'), before)
        self.assertNotEqual(self.client.session.get('active_org_id'), self.foreign.id)


class OrgScopedBoardsTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.user = User.objects.create_user('teo', password='teopass1234')
        cls.org_a = Organization.objects.create(name='Org A')
        cls.org_b = Organization.objects.create(name='Org B')
        OrganizationMembership.objects.create(organization=cls.org_a, user=cls.user, role='admin')
        OrganizationMembership.objects.create(organization=cls.org_b, user=cls.user, role='admin')
        Board.objects.create(owner=cls.user, organization=cls.org_a, name='Tablero A')
        Board.objects.create(owner=cls.user, organization=cls.org_b, name='Tablero B')

    def test_home_lists_only_active_org_boards(self):
        self.client.login(username='teo', password='teopass1234')
        names = {b.name for b in self.client.get(reverse('home')).context['boards']}
        self.assertEqual(names, {'Tablero A'})  # Org A por defecto (orden alfabético)

        self.client.post(reverse('org-switch'), {'organization': self.org_b.id})
        names = {b.name for b in self.client.get(reverse('home')).context['boards']}
        self.assertEqual(names, {'Tablero B'})

    def test_create_stamps_active_org(self):
        self.client.login(username='teo', password='teopass1234')
        self.client.get(reverse('home'))  # org activa = Org A
        self.client.post(reverse('board-create'), {'name': 'Nuevo'})
        board = Board.objects.get(name='Nuevo')
        self.assertEqual(board.organization, self.org_a)


class ThemeRobustnessTests(TestCase):
    def test_save_rejects_invalid_hex(self):
        org = Organization.objects.create(name='Rob Co')
        with self.assertRaises(ValidationError):
            OrganizationTheme.objects.create(organization=org, brand_accent='nothex')

    def test_malformed_hex_in_db_does_not_crash_page(self):
        user = User.objects.create_user('rob', password='robpass1234')
        org = Organization.objects.create(name='Rob Co')
        OrganizationMembership.objects.create(organization=org, user=user, role='admin')
        theme = OrganizationTheme.objects.create(organization=org, brand_accent='#d6ff00')
        # Forzar un valor corrupto saltándose la validación de save() (update()).
        OrganizationTheme.objects.filter(pk=theme.pk).update(brand_accent='zzzzzz')
        self.client.login(username='rob', password='robpass1234')
        resp = self.client.get(reverse('home'))
        self.assertEqual(resp.status_code, 200)  # degrada con gracia, no 500


class FullPaletteThemeTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.user = User.objects.create_user('nsw', password='nswpass1234')
        cls.org = Organization.objects.create(name='NSW', slug='nsw')
        OrganizationTheme.objects.create(
            organization=cls.org,
            brand_accent='#D6FF00', on_accent_mode='auto',
            brand_bg_primary='#EAEAEA', brand_text_primary='#1D1D1D',
            brand_overlay='#1D1D1D', brand_success='#5CE9C3',
            font_display='spacegrotesk', font_body='mulish', theme_mode='light',
        )
        OrganizationMembership.objects.create(organization=cls.org, user=cls.user, role='admin')

    def test_full_light_palette_emitted(self):
        self.client.login(username='nsw', password='nswpass1234')
        html = self.client.get(reverse('home')).content.decode()
        self.assertIn('--brand-bg-primary:234 234 234;', html)   # #EAEAEA
        self.assertIn('--brand-text-primary:29 29 29;', html)    # #1D1D1D
        self.assertIn('--brand-overlay:29 29 29;', html)
        self.assertIn('--brand-success:92 233 195;', html)       # verdiazul
        self.assertIn('--brand-on-accent:17 24 39;', html)       # lima -> negro
        self.assertIn('color-scheme:light;', html)
        self.assertIn('Mulish', html)


# --- v6: creación de workspaces e invitaciones por enlace ---

from organizations.models import OrganizationInvite  # noqa: E402
from organizations.services import (  # noqa: E402
    create_team_organization,
    join_organization,
)


class CreateTeamOrgServiceTests(TestCase):
    def test_creates_team_org_with_owner(self):
        user = User.objects.create_user('u1', password='pass12345')
        org = create_team_organization(user, 'Acme Team', Organization.Brand.NSW)
        self.assertFalse(org.is_personal)
        self.assertEqual(org.brand, Organization.Brand.NSW)
        m = OrganizationMembership.objects.get(user=user, organization=org)
        self.assertEqual(m.role, 'owner')


class OrganizationCreateViewTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user('u1', password='pass12345')
        self.client.login(username='u1', password='pass12345')

    def test_post_creates_and_activates(self):
        resp = self.client.post(reverse('org-create'), {'name': 'Mi Empresa', 'brand': 'flowly'})
        self.assertEqual(resp.status_code, 302)
        org = Organization.objects.get(name='Mi Empresa')
        self.assertFalse(org.is_personal)
        self.assertEqual(self.client.session['active_org_id'], org.id)

    def test_post_empty_name_does_not_create(self):
        self.client.post(reverse('org-create'), {'name': '   ', 'brand': 'flowly'})
        self.assertFalse(Organization.objects.filter(name='').exists())
        self.assertEqual(Organization.objects.filter(is_personal=False).count(), 0)


class InviteManageTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.org = Organization.objects.create(name='Acme')
        cls.manager = User.objects.create_user('boss', password='pass12345')
        cls.member = User.objects.create_user('joe', password='pass12345')
        OrganizationMembership.objects.create(organization=cls.org, user=cls.manager, role='owner')
        OrganizationMembership.objects.create(organization=cls.org, user=cls.member, role='member')

    def _activate(self, username):
        self.client.login(username=username, password='pass12345')
        self.client.post(reverse('org-switch'), {'organization': self.org.id})

    def test_manager_gets_invite_link(self):
        self._activate('boss')
        resp = self.client.get(reverse('invite-manage'))
        self.assertEqual(resp.status_code, 200)
        self.assertTrue(OrganizationInvite.objects.filter(organization=self.org).exists())

    def test_non_manager_forbidden(self):
        self._activate('joe')
        resp = self.client.get(reverse('invite-manage'))
        self.assertEqual(resp.status_code, 403)

    def test_regenerate_changes_token(self):
        self._activate('boss')
        self.client.get(reverse('invite-manage'))
        invite = OrganizationInvite.objects.get(organization=self.org)
        old = invite.token
        self.client.post(reverse('invite-manage'), {'action': 'regenerate'})
        invite.refresh_from_db()
        self.assertNotEqual(invite.token, old)


class InviteAcceptTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.org = Organization.objects.create(name='Acme')
        cls.owner = User.objects.create_user('boss', password='pass12345')
        OrganizationMembership.objects.create(organization=cls.org, user=cls.owner, role='owner')
        cls.invite = OrganizationInvite.objects.create(organization=cls.org, created_by=cls.owner)
        cls.newcomer = User.objects.create_user('newbie', password='pass12345')

    def test_accept_joins_org(self):
        self.client.login(username='newbie', password='pass12345')
        resp = self.client.post(reverse('invite-accept', args=[self.invite.token]))
        self.assertEqual(resp.status_code, 302)
        self.assertTrue(
            OrganizationMembership.objects.filter(organization=self.org, user=self.newcomer).exists()
        )
        self.assertEqual(self.client.session['active_org_id'], self.org.id)

    def test_accept_is_idempotent(self):
        self.client.login(username='newbie', password='pass12345')
        self.client.post(reverse('invite-accept', args=[self.invite.token]))
        self.client.post(reverse('invite-accept', args=[self.invite.token]))
        self.assertEqual(
            OrganizationMembership.objects.filter(organization=self.org, user=self.newcomer).count(), 1
        )

    def test_invalid_token_404(self):
        self.client.login(username='newbie', password='pass12345')
        resp = self.client.get(reverse('invite-accept', args=['nope-not-a-token']))
        self.assertEqual(resp.status_code, 404)

    def test_join_service_uses_invite_role(self):
        membership = join_organization(self.newcomer, self.invite)
        self.assertEqual(membership.role, 'member')
